### ISSUE TITLE
 SolverError: Solver 'GUROBI' failed. Try another solver, or solve with verbose=True for more information.

### ISSUE THREAD

**Issue by eeenadeem** [TUMCREATE-ESTL/FLEDGE.jl#26]
I have installed all the packages and followed the steps as given for anaconda.

but am getting the above error,
please help me.

SolverError: Solver 'GUROBI' failed. Try another solver, or solve with verbose=True for more information.

**Comment by stroitzsch** [comment]
Hi there, just picking up the work here.

Is this still an issue & should I look into it, or is it out of date?

(Note that I have just moved development to Python 3.10, please try again with the latest setup.)
